### PR TITLE
Making exception-swallowing optional

### PR DESCRIPTION
**Pull request by deobald**
- we ran into a bug where one of our older excel templates was failing
  `render-to-file` when it was read but this wasn't causing the build to
  fail because the exception is swallowed (printed to console)
- to avoid changing legacy API behaviour, I've added an option to throw
  exceptions; consumers of `excel-templates` don't need to change how
  they call `render-to-file` to keep the same behaviour (if they were
  perhaps expecting exceptions to be swallowed)
- on a major version change in the future, it would be nice if this flag
  were reversed to become: `{:swallow-exceptions true}` so the safe
  behaviour (throwing exceptions) becomes the default.

- added a small test suite, which requires clojure as a dependency to
  run normally. also added cider to make the tests easy to run during
  development.

### CODE REVIEW

**Comment by deobald** [comment]
@tomfaulhaber Please do let me and/or @timothyandrew know if there's anything we can do to help get this merged. :)

**Comment by tomfaulhaber** [comment]
I'm confused by the whole direction of this. Why wouldn't we just remove the code that swallows exceptions? I'll have to look at the code that does this and its history, but that just strikes me as a mistake.

**Comment by deobald** [comment]
@tomfaulhaber That would be vastly preferable. I assumed the exceptions were being swallowed intentionally... for whatever reason... because I couldn't think of why else that code would be there. :) If they always bubble up, even better!

Thanks! /cc @timothyandrew

PS: If you are busy and want us to open another PR to remove the exception-swallowing code, we can take a look at that too.

**Comment by tomfaulhaber** [comment]
I checked the history and see that this exception swallowing is just an accident and is never desirable. I filed #17 to resolve that and am closing this pull request. Thanks for noticing this, @deobald!

**Pull request closed without merging**
